services:
  web:
    container_name: apimediaplay
    build: .
    volumes:
      - .:/app
    ports:
      - 5001:5000
    networks:
      - mediaplayer-network
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
        restart: true
  db:
    image: postgres:16.2-alpine3.19
    container_name: dbmediaplay
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - 5426:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      start_period: 5s
      timeout: 3s
      retries: 3
    networks:
      - mediaplayer-network
    env_file:
      - .env

volumes:
  db_data:

networks:
  mediaplayer-network:
    name: netmediaplayer