"""Add media table

Revision ID: 95b28bfedf78
Revises: 
Create Date: 2024-10-09 10:57:52.651894

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '95b28bfedf78'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('media',
    sa.Column('media_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('media_id'),
    sa.UniqueConstraint('url')
    )
    op.create_index('title_idx', 'media', ['title'], unique=False)
    op.create_index('title_url_idx', 'media', ['title', 'url'], unique=False)
    op.create_index('url_idx', 'media', ['url'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('url_idx', table_name='media')
    op.drop_index('title_url_idx', table_name='media')
    op.drop_index('title_idx', table_name='media')
    op.drop_table('media')
    # ### end Alembic commands ###
